### ISSUE TITLE
Gasverbruik historie ontbreekt 

### ISSUE THREAD

**Issue by hennykarreman** [Inversion-NL/Toon-Android#54]
Ik heb de Android App geinstalleerd.
Het aanmelden gaat de eerste keer goed, maar is al snel niet meer mogelijk.
Cache legen lost dit probleem tijdelijk weer op.
Eigenlijk onbruikbaar dus.

Als de app verbonden is wordt de gashistorie niet weergegeven.

Als ik de ruwe data wil verzamelen lukt dat niet omdat de Toon dan niet gevonden wordt.

Graag een oplossing.

Mvg

Henny Karreman

**Comment by RoadXY** [comment]
Vwb je eerste probleem: dit zou opgelost moeten zijn in 0.7.2 welke over een tijdje beschikbaar zou moeten komen (als er geen problemen gevonden worden).

Gas historie is helaas niet meer mogelijk sinds een update door Toon.
We hebben nog geen manier gevonden om deze weer op te vragen op de Toon, helaas.
