### ISSUE TITLE
Toon for Android (Aangepaste Toon) werkt niet meer

### ISSUE THREAD

**Issue by pcorreia72** [Inversion-NL/Toon-Android#55]
The app doesn't work anymore. I tried to flush the firewall rules. I removed the app several times. The only thing I could not find, was the clearing of the cache. 
The error i got from Z-wave is:

Er is een fout opgetreden bij het verbinden naar uw Toon:

com.android.volley.VolleyError:
java.lang.IllegalArgumentException: name is empty

Can you please advise on how to proceed?
Thanks in advance. 

Kind regards 
Patrick

**Comment by RoadXY** [comment]
Could you try to resolve the issue by the steps lined out here:
https://www.inversion.nl/hobbies/android-applications/toon-for-android/support-voor-toon-for-android/

**Comment by RoadXY** [comment]
Closed due to inactivity.
You can always reopen this issue by replying here.
